apiVersion: v1
kind: Service
metadata:
  name: loginapp-service
  labels:
    app: loginapp
    tier: frontend

spec:
  selector:
    app: loginapp
    tier: frontend
  
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
